#!/bin/bash
#PBS -l nodes=4:ppn=32:xe
#PBS -l walltime=00:15:00
#PBS -N GMX-CoCoMD
#PBS -q high

# Make sure any symbolic links are resolved to absolute path 
#export PBS_O_WORKDIR=$(readlink -f $PBS_O_WORKDIR)
export OMP_NUM_THREADS=1
# Change to the directory that the job was submitted from 
# (remember this should be on the /work filesystem) 
cd $PBS_O_WORKDIR
export TMPDIR=$PBS_O_WORKDIR/TMPDIR
source /u/sciteam/suess/ve-coco/bin/activate
source /u/sciteam/suess/gromacs/gromacs-2018.4/bin/GMXRC

which gmx_mpi

#python multi2.py

aprun -n 128 -N 32 gmx_mpi grompp -f run1.mdp -c bpti.gro -p topol.top -o testBW.tpr -maxwarn 1
